### ISSUE TITLE
createStubInstance is not exposes when using sinon-test?

### ISSUE THREAD

**Issue by StylishFlash** [sinonjs/sinon-test#102]
Versions used:

- node: 8.10.0
- sinon: 7.2.7
- sinon-test: 2.4.0
- mocha: 6.0.2
- typescript: 3.3.3333
- ts-node: 8.0.2

In Sinon we can do the following (sandbox.spec.ts):
````
import * as sinon from "sinon";
import {SinonSandbox} from "sinon";

describe("sandbox", function() {

    class MyClass {

    }

    it("test 1", function() {
        const sandbox: SinonSandbox = sinon.createSandbox();
        sandbox.createStubInstance(MyClass);
        sandbox.restore();
    });

});
````
So using sinon-test I tried:
````
import * as sinon from "sinon";
import {SinonSandbox} from "sinon";

const sinonTest = require("sinon-test");
const test = sinonTest(sinon);

describe("sandbox", function() {

    class MyClass {

    }

    it("test 1", test(function(this: SinonSandbox) {
        this.createStubInstance(MyClass);
    }));

});
````
But when running with Mocha this throws:
````
 1) sandbox
       test 1:
     TypeError: this.createStubInstance is not a function
      at Context.<anonymous> (test\sandbox.spec.ts:14:14)
      at callSandboxedFn (node_modules\sinon-test\lib\test.js:93:25)
      at Context.sinonSandboxedTest (node_modules\sinon-test\lib\test.js:113:24)
````
However when replacing ``this.createStubInstance(MyClass)`` with ``this.stub(MyClass)`` the test passes.

According to the documentation the test() wrapper should create a context based on a Sinon sandbox.
So how come ``createStubInstance`` is not available? Am I missing something?
What is the actual type of ``this`` within the wrapper's context? What is the correct way to do this?

**Comment by fatso83** [comment]
Normally I would reply with the standard "usage questions should be asked in stack overflow", but this actually touches upon a kind of API deviation, so I'll answer you.

A sandbox is supposed to shield the environment from you. In Sinon's case, this means it restores the methods that have been stubbed or wrapped in spies. But `createStubInstance` is not stubbing any methods on any existing entity. It is creating a _new object_, using the existing constructor, and then adding stubs in place of the methods of that object's prototype. So there isn't really much for a sandbox to do in this sense, which is  _perhaps_ why the original author of the `sinon.test` method (when that was part of the main `sinon` package) chose not to expose that method, since it didn't really make sense.

Still, you are right to wonder, because _it is present on the "normal" sandbox_. And since we are supposed to give the impression of wrapping the functions in a sandbox, this is an omission, I would say. Why this is, I am not sure. I can have a quick peek to try and see ...

**Comment by StylishFlash** [comment]
I apologize for not first considering to post it on stack overflow.
I understand what you are saying.
So does this mean that we are suppose to use it like this:
````
    it("test 1", test(function(this: SinonSandbox) {
        sinon.createStubInstance(MyClass);
        this.stub(MyClass);
    }));
````
Because the usage of ``sinon`` & ``this`` within similar context seems confusing as a reader?

**Comment by fatso83** [comment]
As I said, I understand it is confusing to not have API parity, and I don't know why it doesn't work. From browsing the code it looks like it SHOULD work, as it OS exposed in the sandbox API, so this needs some debugging, which I don't have time for at the moment. Feel free to dig, and if you find out, we accept pull requests :-)

**Comment by fatso83** [comment]
I spent well over an hour digging into this. Basically you are touching upon a part of the Sinon source code / feature set which is poorly documented, and for which there is little background to help us understand why is as it is (I looked at the tests, the original commits, etc).

As you probably know, `sinon-test` accepts an optional configuration object that can be used to configure the sandbox. Among the list of config options are `properties`, which lists which properties are _whitelisted_ for injection into the object you want to inject the sandbox' properties into (the `injectInto` property of the config).

Unfortunately, it doesn't help to add `createStubInstance` to the list of properties:
```javascript
const test = sinonTest(sinon, {properties: ["spy", "createStubInstance"]});
```

All this does is give you a context object (`this`) with a single method: `this.spy`. So why is `createStubInstance` not exposed? It is because it's actively being [filtered away in the `sandbox.inject()` method](https://github.com/sinonjs/sinon/blame/v7.0.0/lib/sinon/sandbox.js#L61). There are only 7 properties that `inject` considers kosher - all others [are filtered out](https://github.com/sinonjs/sinon/blame/v7.0.0/lib/sinon/create-sandbox.js#L53-L57).

This only affects those people using `injectInto`, which I suspect is very few of the "normal" direct users of Sinon. All users of `sinon-test` are implicitly being affected by this, though, but of those, very few try out more than the "most popular" methods. So kudos to you for going your own ways :smile: 

I think the basic fix for this is basically to fix Sinon: change `inject` to allow some of the newer methods to be exposed and then change the [default config](https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/core/default-config.js) of Sinon (and/or [the default config of `sinon-test`](https://github.com/sinonjs/sinon-test/blob/master/lib/default-config.js)) to expose these props.

**Comment by StylishFlash** [comment]
Yes, I also already noticed that the default properties did not include ``createStubInstance``.

Based on the code you linked I would agree and say that adding the methods to ``sandbox.inject()`` would be a small non-breaking change as these methods already exist on sandbox itself anyway.

Current available workarounds are:
1. Using ``sinon.createStubInstance`` within sinon-test context as mentioned above.
2. Not using sinon-test at all and use normal sinon sandbox. This means each of your test suites would have to include:
````
    let sandbox: SinonSandbox;

    beforeEach(() => {
        sandbox = sinon.createSandbox();
    });

    afterEach(() => {
        sandbox.restore();
    });
````
Which I think isn't too bad for now.

**Comment by fatso83** [comment]
This should be fixed if you install Sinon 7.3 :)

**Comment by StylishFlash** [comment]
It now works if I pass ``createStubInstance`` to the ``properties``.
````
const sinonTestConfig = {
    properties: ["createStubInstance"]
};
const test = sinonTest(sinon, sinonTestConfig);
````
I would expect it to be available by default.
But I suspect this is because ``@types/sinon-test`` still needs to be updated as the latest version ``1.0.7`` uses
````
interface Configuration {
    injectIntoThis?: boolean;
    injectInto?: any;
    properties?: Array<"spy"| "stub"| "mock"| "clock"| "server"| "requests">;
    useFakeTimers?: boolean;
    useFakeServer?: boolean;
}
````

**Comment by fatso83** [comment]
I did something wrong here, but forgot about fixing it up. Thanks for the reminder. I'll reopen this to not forget.

**Comment by StylishFlash** [comment]
Any idea on when you will have time to finish this?

**Comment by fatso83** [comment]
Oooh, totally forgot about this. I remember it was something somewhat complex and that there were multiple moving parts (the main sinon project and this) and I don't remember it all very well anymore ... There is too much stuff on my plate right now. I can try to pick it up again in a week or two (adding a reminder to my calendar now).

**Comment by fatso83** [comment]
OK, I did some code archeology to dig into this, going back to Sinon 0.2.3. 

To fix this issue, all that is needed (I just verified) is to revert this commit in Sinon: https://github.com/sinonjs/sinon/pull/1994/commits/73d2ac8e320682fee3041b3acfdf9b9db7b12bdd. That adds the `injectIntoThis` prop. But as the commit says, it is not used _anywhere_ in the main Sinon project, so it doesn't feel great to add something back in that is basically just used in this sub project.

That prompted me to follow the piece of code back in time using `git blame`, ending up with this initial commit by @cjohansen in 2010: https://github.com/sinonjs/sinon/commit/018dfb4e7. It was basically introduced to [support the basis for what is now the `sinon-test` module](https://github.com/sinonjs/sinon/commit/018dfb4e7#diff-9e5be644455d1a414a715b793926c72eR303), then called `sinon.test`.

The reason this module broke after removing `injectIntoThis` from the main Sinon module was that it is sets `injectIntoThis: true` in Sinon's default sandbox config, and `sinon-test` [actively checks for this](https://github.com/sinonjs/sinon-test/blob/0e5dc5f/lib/test.js#L85). So by adding `injectIntoThis: true` as part of this module's default config should fix this issue.

Trying this ASAP.

**Comment by fatso83** [comment]
@StylishFlash The latest release basically makes `sinon-test` work with newer Sinon releases, which was the biggest issue. 

I tested the use case described in https://github.com/sinonjs/sinon/pull/1994#issue-260537379, which makes me assume everything works as intended:

```bash
mkdir foo
cd foo
npm init -y
npm i sinon-test
npm i sinon
npm i mocha
npm i esm

mocha -r esm mytest.js 


  sandbox
    ✓ test 1


  1 passing (6ms)
```
