### ISSUE TITLE
'this' is globalThis inside test block when using @hapi/lab

### ISSUE THREAD

**Issue by pat-flew** [sinonjs/sinon-test#165]
Hey, not sure whether this belongs here or at lab, or if I'm just doing something wrong, but this test is failing for me:

```js
// 'use strict';

const sinon = require('sinon');
const sinonTest = require('sinon-test');
const test = sinonTest(sinon);

const Code = require('@hapi/code');
const Lab = require('@hapi/lab');
const lab = (exports.lab = Lab.script());
const { it, describe } = lab;

const assert = require('assert');

describe('sinon-test', function() {
  it(
    'this should not be globalThis',
    test(function() {
      assert.notEqual(this, globalThis);
    })
  );
});
```

**Comment by fatso83** [comment]
Ha, I do think you have stumbled upon a bug in `sinon-test` here, and I am not quite sure what to think.

Your example _actually runs fine_ on RunKit using Node 12:
https://runkit.com/fatso83/sinon-test-165
:thinking: 

BUT if I use `require("@fatso83/mini-mocha").install();` instead of Hapi, though, I get it to fail.

It _does fail_ when I check it out locally and run `node test.js`, but if I comment out the hapi stuff and then run it using Mocha it is fine again :sweat: 

Mocha does set up contexts of its own, though, so that is possibly what is making it run differently in Mocha and also why we haven't caught on to this before.

If nothing else, this is at least an interesting issue :smiley:

**Comment by fatso83** [comment]
OK, thinking about this a little, and browsing our code, this is not really a BUG but a FEATURE REQUEST. All `sinon-test` promises is to expose the sandbox hooks on the current context (`this`). It does not _create_ a new context, it uses the one passed to it. 

Mocha creates a new context for every test, which means that if Sinon had created a new context itself _by default_, then none of the hooks provided by Mocha itself, such as `this.timeout()` and friends, would work, as they would be hidden by the new context created by Sinon.

Seeing that Mocha is (or was? Jest is up there) the most popular test runner, that would not be such a good fit for most users.

But you are not using Mocha, and so you see a new need :-) I see two opt-in features possible:
1. An option to create a fresh new `this` context per function.
2. An option to create a new `this` context per function that has the previous `this` as its prototype, thus exposing its functions and values. Not quite sure of the ramifications, though ...

**Comment by pat-flew** [comment]
Hey @fatso83, thanks! That all makes sense, and provides a lot of context. 👍 

First time with both Sinon and Hapi so take my input with a grain of salt but option 1 ought to cover my use-case. 

It's a fresh project so after I wrote this I had a look at swapping in Mocha which worked as expected so it's not a show-stopper

**Comment by fatso83** [comment]
After thinking a little more, we already have this feature, kind of :-)

Sinon-test is just a little wrapper using a standard sinon sandbox, and so can be configured with all the standard settings for normal sandboxes, including [`injectInto`](https://sinonjs.org/releases/latest/sandbox#injectinto). Normally, `sinon-test` will inject all the sandbox props into `this`, but if that is not what you want, you can just assign it to some other object. 

```
const ctx = {};
const test = sinonTest(sinon, { injectInto: ctx });
```

should do what you want. You know have all the sandbox props on `ctx`, meaning `ctx.stub()`, `ctx.spy()`, etc.


That being said, since Sinon is using a sandbox internally by default, you can also opt to just use that instead of `sinon-test` at the cost of a `afterEach(() => sinon.restore())`, which is what `sinon-test` saves you :)
