### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by lawrencec** [sinonjs/sinon-test#41]
Hi,

What's the status of this project? Since the initial release 11 months ago, there have been numerous issues fixed but no new release published. I'd like to start using `sinon-test` in my projects but the unpublished fixes are blocking me. 

Could we please have an update on the current status and what, if anything, is blocking a release? Perhaps, if required, the community can help out.

Thanks

Loz

**Comment by fatso83** [comment]
There is nothing preventing you from using sinon-test directly from GH. Just change the version to `"sinon-test" : "github:sinonjs/sinon-test"`. 

`sinon-test` was split out from the main project to let the Sinon maintainers focus on the core and let the community handle the not-so-vital utilities like `sinon-test`, XHR stubbing and the mocks (the latter two will probably be split out in time for Sinon 3). Unfortunately, even though we had volunteers that signed up for the maintenance work, the only maintainer work done on sinon-test since the split has been done by the core maintainers: me and @fearphage, so the plan hasn't really been all that effective, but at least we don't get the noise in the main project.

I can ship a new version now, but we are still hoping for someone to step up so we don't have to.

**Comment by fatso83** [comment]
Version 1.0 is now out 🎉

**Comment by lawrencec** [comment]
Wow, talk about service! :) Thanks.

Yeah, I knew I could specify a github url but my project is a wrapper util for tests. I wouldn't want downstream projects that used it to be affected if there was any issue on master.

Thanks for all your work on sinon, I've been using it for a long long time.

**Comment by fatso83** [comment]
Sure, no problem, but for later reference, you could always specify a specific commit as well: `sinonjs/sinon-test#025e0dbb`. That way no work done on any branch would affect your downstream projects.
